config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'

  get '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :bases
  resources :users do
    collection { post :import }
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      patch 'update_index'
      # 勤怠変更申請
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'  
      # １ヶ月承認
      get 'attendances/edit_month_approval'
      patch 'attendances/update_month_approval'
      # 確認のshowページ
      get 'verifacation'
    end
    collection do
      get 'working'
    end
    resources :attendances, only: [:update] do
      member do
        # 残業申請モーダル
        get 'edit_overtime_request'
        patch 'update_overtime_request'
        # 残業申請お知らせモーダル
        get 'edit_overtime_notice'
        patch 'update_overtime_notice'
        # 残業申請確認モーダル
        get 'show_overtime_verifacation'
        # 勤怠変更お知らせモーダル
      get 'edit_one_month_notice'
      patch 'update_one_month_notice'
        #１ヶ月承認モーダル
      get 'edit_month_approval_notice'
      patch 'update_month_approval_notice'
      # 勤怠ログ
      get 'log'
      end
    end 
  end
  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :basic_work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  

  def self.import(file)
    CSV.foreach(file.path, encoding: 'cp932:utf-8',headers: true) do |row|
      user = find_by(id: row["id"]) || new
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save!(:validation => false)
    end
  end

  def self.updatable_attributes
      ["name","email","affiliation","employee_number","uid", "basic_work_time", 
        "designated_work_start_time", "designated_work_end_time","superior","admin","password"]
  end




  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :update_index, :edit_basic_info, :destroy,:overtime_request]
  before_action :logged_in_user, only: [:show, :update, :update_index, :destroy, :edit_basic_info,:overtime_request]
  before_action :correct_user, only: [ :edit,:update]
  before_action :set_one_month, only: [:show]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :index, :working]
  before_action :admin_not, only: [:show]
  before_action :correct_not, only: [:show]

  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
    @overtime = Attendance.where(indicater_reply: "申請中", indicater_check: @user.name).count
    @change = Attendance.where(indicater_reply_edit: "申請中", indicater_check_edit: @user.name).count
    @month = Attendance.where(indicater_reply_month: "申請中", indicater_check_month: @user.name).count
    @superior = User.where(superior: true).where.not( id: current_user.id )
    @attendance = @user.attendances.find_by(worked_on: @first_day)
    # csv出力
    respond_to do |format|
      format.html
      filename = @user.name + "：" + l(@first_day, format: :middle) + "分" + " " + "勤怠"
      format.csv { send_data render_to_string, type: 'text/csv; charset=shift_jis', filename: "#{filename}.csv" }
    end
  end


  def index
      @users = User.where.not(id: 1)
      respond_to do |format|
      format.html do
      end
      format.csv do
        send_data render_to_string,filename:"original_filename.csv",type: :csv
      end
    end
  end 

  def import 
    if params[:file].blank?
      flash[:danger]= "csvファイルを選択してください"
      redirect_to users_url
    elsif 
      File.extname(params[:file].original_filename) != ".csv"
      flash[:danger]= "csvファイル以外は出力できません"
      redirect_to users_url
    else
      User.import(params[:file]) 
      flash[:success]= "インポートが完了しました"
      redirect_to users_url
    end

  rescue ActiveRecord::RecordInvalid
    flash[:danger]= "不正なファイルのため、インポートに失敗しました"
    redirect_to users_url
  rescue ActiveRecord::RecordNotUnique
    flash[:danger]= "既にインポート済です"
    redirect_to users_url
  end
  



  def update_index
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to users_url
    else
      flash[:danger] = "更新に失敗しました。"
      redirect_to users_url
    end 
  end 

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new 
    end  
  end 

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit 
    end 
  end  

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
  end 

  def working 
    # ユーザーモデルから全てのユーザーに紐づいた勤怠たちを代入
    @users = User.all.includes(:attendances)
end 



  def verifacation
    @user = User.find(params[:id])
    # お知らせモーダルの確認ボタンを押した時にparams[：worked_on]にday.worked_onを入れて飛ばしたので、それをfind_byで取り出している
    @attendance = Attendance.find_by(worked_on: params[:worked_on])
    @first_day = @attendance.worked_on.beginning_of_month
    @last_day = @first_day.end_of_month
    @attendances = @user.attendances.where(worked_on: @first_day..@last_day).order(:worked_on)
    @worked_sum = @attendances.where.not(started_at: nil).count
  end  

  


  private

    def user_params
      params.require(:user).permit(:name, :email, :affiliation,:employee_number,:uid, :password, 
        :password_confirmation, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
    end

    
  end

app/helpers/users_helper.rb
module UsersHelper
  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_overtime_request.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">残業申請</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @attendance, url: edit_overtime_request_user_path(@attendance), local: true, method: :patch) do |f| %>
        <table class="table table-bordered table-condensed overtime-table">
          <thead>
            <th>日付</th>
            <th>曜日</th>
            <th>終了予定時間</th>
            <th>翌日</th>
            <th>業務処理内容</th>
            <th>指示者確認
              <div class="maru size_small black">       
                <div class="letter3">印
              </div> 
            </th>
          </thead>
          <tbody>
          <%= @attendances.each do |day| %>
            <%= f.filds_for "attendances[]",day do |attendance|%>
            <% css_class = 
            case $days_of_the_week[day.worked_on.wday]
              when '土'
                'text-primary'
              when '日'
                'text-danger'
              end
              %>
            <td><%= l(day.worked_on, format: :short) %></td>
            <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
            <td><%= f. time_select :overtime_finished_at,{class: "form-control bootstrap-date-only-width"} %></td>
            <td><%= f.check_box :tomorrow,id: "tomorrow" %></td>
            <td><%= f.text_fild :overtime_work, class:"form-control" %></td>
            <td><%= f.select :indicater_check,{'なし':1, '申請中':2, '承認':3, '否認':4},{ class: 'form-control input-sm' , required: true } %></td>
          </tbody>
        </table>
            <%= f.submit "変更を送信する", class: "btn btn-primary btn-block" %>
            <% end %>
        <% end %>
      <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user,local: true) do |f| %>
   <%= render 'shared/error_messages',object: @user%>

   <%= f.label :name, class: "label-#{yield(:class_text)}" %>
   <%= f.text_field :name, class: "form-control" %>

   <%= f.label :email, class: "label-#{yield(:class_text)}" %>
   <%= f.email_field :email, class: "form-control" %>

   <%= f.label :affiliation, class: "label--#{yield(:class_text)}" %>
   <%= f.text_field :affiliation, class: "form-control", min: 0  %>

   <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
   <%= f.number_field :employee_number, class: "form-control", min: 0  %>

   <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
   <%= f.number_field :uid, class: "form-control" %>

   <%= f.label :password, class: "label-#{yield(:class_text)}" %>
   <%= f.password_field :password, class: "form-control" %>

   <%= f.label :password_confirmation, class: "label--#{yield(:class_text)}" %>
   <%= f.password_field :password_confirmation, class: "form-control" %>

   <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
   <%= f.time_field :basic_work_time, class: "form-control" %>

   <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
   <%= f.time_field :designated_work_start_time, class: "form-control" %>

   <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
   <%= f.time_field :designated_work_end_time, class: "form-control" %>
<div class = "post">
   <%= f.submit "更新", class: "btn btn-primary btn-block btn-user-#{yield(:class_text)}" %>
</div>   
   <% end %>

app/views/users/_form2.html.erb
    <%= form_with(model: user, url: update_index_user_path(user), local: true, method: :patch) do |f| %>
    <%= render 'shared/error_messages',object: user %>

    <%= f.label :name, class: "label-#{yield(:class_text)}" %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :email, class: "label-#{yield(:class_text)}" %>
    <%= f.email_field :email, class: "form-control" %>

    <%= f.label :affiliation, class: "label--#{yield(:class_text)}" %>
    <%= f.text_field :affiliation, class: "form-control" %>

    <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
    <%= f.number_field :employee_number, class: "form-control", min: 0  %>

    <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
    <%= f.number_field :uid, class: "form-control", min: 0 %>

    <%= f.label :password, classy: "label-#{yield(:class_text)}" %>
    <%= f.password_field :password, class: "form-control" %>

    <%= f.label :password_confirmation, class: "label--#{yield(:class_text)}" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>

    <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
    <%= f.time_field :basic_work_time, class: "form-control" %>

    <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
    <%= f.time_field :designated_work_start_time, class: "form-control" %>

    <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
    <%= f.time_field :designated_work_end_time, class: "form-control" %>
<div class = "post">
    <%= f.submit "更新", class: "btn btn-primary btn-block btn-user-#{yield(:class_text)}" %>
</div>    
    <% end %>

app/views/users/_form3.html.erb
<%= form_with(model: @user,local: true) do |f| %>
  <%= render 'shared/error_messages',object: @user%>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :affiliation, class: "label--#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>

  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :employee_number, class: "form-control", min: 0 %>

  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :uid, class: "form-control", min: 0 %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label--#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>

  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>

  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>
<div class = "post">
  <%= f.submit "新規登録", class: "btn btn-primary btn-block btn-user-#{yield(:class_text)}" %>
</div>   
  <% end %>

app/views/users/attendance_index.html.erb
<% provide(:title, "index") %>
<h1>出勤中社員一覧</h1>

<div>
  <table class="table table-bordered table-condensed id="table-attendance-index">
    <tr>
      <th>社員番号</th>
      <th>名前</th>
    </tr>

    <% @users.each do |user|%>
      <tr>
        <td><%=user.staff_id %></td>
        <td><%=user.name %></td>
      </tr>
    <%end%>  
  </table>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<h1>ユーザー情報の更新</h1>

<div class="row">
 <div class="col-md-6 col-md-offset-3">
  <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "edit_basic_info") %>
<h1>基本情報の修正</h1>

app/views/users/index.html.erb
<% provide(:title, "index") %>
<h1>ユーザー一覧</h1>

<div class="col-md-3 col-md-offset-9">
    <h5>ユーザー名検索</h5>
      <%= form_with url: users_path, method: :get, local: true do |f| %>
      <div class="form-inline">
        <div class="input-group col-xs-12 hidden-xs">
          <span class="input-group">
            <%= f.text_field :search, placeholder: 'キーワード入力' , class: "form-control" %>
          </span>
            <%= f.submit '検索', :name => nil, class: "btn btn-primary" %>
      <% end %> 
      </div>
    </div>
  </div>

<div class="csv">
  <%= form_tag import_users_path,multipart: true do |f|%>
    <%= file_field_tag :file %>
    <%= submit_tag "CSV出力",class: "btn btn-primary"%>
<% end %>
</div>  

  <% @users.each do |user| %>
    <p>
      <%= user.name %><br>
        |&nbsp<%= link_to "削除", user, method: :delete,data: { confirm: "#{user.name}を削除してよろしいですか？" },
        class: "btn btn-primary btn-default" %><br>
        <div class="panel-group">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <button type="button" data-toggle="collapse" href="#collapse<%= user.id %>" 
                class="btn btn-primary">編集</button>
              </h4>
            </div>
              <div id="collapse<%= user.id %>" class="panel-collapse collapse">
                <div class="panel-body"><%= render 'form2', user: user %></div>
            </div>
          </div>
        </div>
      </p>
    <% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>ユーザー登録</h1>

<div class="row">
<div class="col-md-6 col-md-offset-3">
  <%= render 'form3' %>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <div class="btn-users-show">
          <%= link_to "◀︎",user_path(date: @first_day.prev_month),class: "btn btn-primary" %>
          &nbsp;&nbsp;
          【<%= l(@first_day, format: :middle) %>】
          時間管理表
          &nbsp;&nbsp;
          <%= link_to "▶︎",user_path(date: @first_day.next_month),class: "btn btn-primary" %>
        </div> 
      </td>
      <td> 
        指定勤務開始時間：<%= format_basic_info(@user.designated_work_start_time) %><br>
        指定勤務終了時間：<%= format_basic_info(@user.designated_work_end_time) %>
      </td>
      <td colspan="3">基本時間：<%= format_basic_info(@user.basic_work_time) %></td>
      <td>初日<%= l(@first_day, format: :short) %></td>
    </tr>
    <tr>
      <td>所属：<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>名前：<%= @user.name %></td>
      <td>コード：<%= @user.employee_number %></td>
      <td></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締め<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<div class="notice-group">
  <% if current_user.superior? %>
    <% if @month >= 1  %>
      <div class="red-group">
        <p><%= link_to  "【所属長承認申請のお知らせ】", edit_month_approval_notice_user_attendance_path(@user, @month), remote: true, class: "notice" %><span class="red_box"><%= "#{@month}件の通知があります"%></span></p>
      </div>    
      <% else %>
      <p clas="notice">【所属長承認申請のお知らせ】</p>
      <% end %> 
<p></p>
      <% if @change >= 1  %>
        <div class="red-group">
          <p><%= link_to  "【勤怠変更申請のお知らせ】", edit_one_month_notice_user_attendance_path(@user, @change), remote: true, class: "notice" %><span class="red_box"><%= "#{@change}件の通知があります"%></span></p>
        </div>  
      <% else %>
        <p clas="notice">【勤怠変更申請のお知らせ】</p>
      <% end %> 

      <% if @overtime >= 1  %>
        <p><%= link_to  "【残業申請のお知らせ】", edit_overtime_notice_user_attendance_path(@user, @overtime), remote: true, class: "notice" %><span class="red_box"><%= "#{@overtime}件の通知があります"%></span></p>
      <% else %>
        <p clas="notice">【残業申請のお知らせ】</p>
      <% end %> 
  <% end %>
</div>

  <%= link_to "勤怠を編集",attendances_edit_one_month_user_path(date: @first_day),class: "btn btn-primary" %> &nbsp;
  <%= link_to "CSV出力",user_path(format: 'csv'),class: "btn btn-primary" %><br>
  <%= link_to "勤怠修正ログ（承認済）",log_user_attendance_path(@user, @attendance),class: "btn btn-primary" %>
<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan ="3">残業申請</th>
        <th rowspan ="3">日付</th>
        <th rowspan ="3">曜日</th>
        <th colspan="8">【実績】</th>
        <th colspan="5">【所定外勤務】</th>
      </tr>
      
      <tr>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan ="2"valign="bottom">在社時間</th>
        <th rowspan ="2">備考</th>
        <th colspan="2" >終了予定時間</th>
        <th rowspan ="2">時間外残業</th>
        <th rowspan ="2">業務処理内容</th>
        <th rowspan ="2">
          指示者確認<div class="maru size_small black">       
          <div class="letter3">印</div>
      </tr>

      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>

    <tbody tbody class="line">
    <% @attendances.each do |day| %>
          <% css_class = 
            case $days_of_the_week[day.worked_on.wday]
              when '土'
                'text-primary'
              when '日'
                'text-danger'
              end
              %>

        <tr>
          <td><%= link_to "残業申請", edit_overtime_request_user_attendance_path(@user,day), remote: true , class: "btn btn-primary" %></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td><%= l(day.started_at,format: :hour) if day.started_at.present? %></td>
          <td><%= l(day.started_at,format: :minute) if day.started_at.present? %></td>

          <td>
            <% if btn_text = attendance_state_start(day) %>
              <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>

          <td><%= l(day.finished_at,format: :hour) if day.finished_at.present? %></td>
          <td><%= l(day.finished_at,format: :minute) if day.finished_at.present? %></td>
          <td>
            <% if btn_text = attendance_state_finish(day) %>
              <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at, day.finished_at) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <% if day.indicater_reply == "承認" %>
            <td><%= day.overtime_finished_at.try(:strftime,"%H") %></td>
            <td><%= day.overtime_finished_at.try(:strftime,"%M") %></td>
            <% if day.overtime_finished_at.present? %> 
              <td><%= overtime_worked_on(day.overtime_finished_at, @user.designated_work_end_time, day.tomorrow) %></td>
            <% else %>
              <td></td>
            <% end %>
            <td><%= day.overtime_work %></td>
          <% else %>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          <% end %>
          <td>
            <p>
              <% if day.indicater_check.present? %>
                <%= "#{day.indicater_check}に残業#{day.indicater_reply}" %>
              <% elsif day.indicater_reply == "承認" %>
                <%= "残業申請が#{day.indicater_reply}されました" %>
              <% elsif day.indicater_reply == "否認" %>
                <%= "残業申請が#{day.indicater_reply}されました" %>
              <% end %>
            </p>
            <p>
              <% if day.indicater_check_edit.present? %>
                <%= "#{day.indicater_check_edit}に勤怠変更#{day.indicater_reply_edit}" %>
                <% elsif day.indicater_reply_edit == "承認" %>
                <%= "勤怠変更申請が#{day.indicater_reply_edit}されました" %>
              <% elsif day.indicater_reply_edit == "否認" %>
                <%= "勤怠変更申請が#{day.indicater_reply_edit}されました" %>
              <% end %>
            </td>
            </p>
        </tr>
      <% end %>
    </tbody>

    <tfoot>
      <tr>
        <td></td>
        <td colspan="2">累計日数<br>
          <%= @attendances.count %>日</td>
        <td colspan="6">総合勤務時間<br>
        <%= format_basic_info(@user.basic_work_time).to_f * @worked_sum %>
          </td>
        <td>累計在社時間<br>
          <%= format("%.2f", @total_working_times.to_f) %></td>
        <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <%
=begin%>
 1ヶ月申請 
<%
=end%>
        <td>
          <%= form_with(model: @user, url: attendances_update_month_approval_user_path(@user), method: :patch , local: true) do |f| %> 
              <%= f.hidden_field :indicater_reply_month, :value => "申請中" %>
              <%= f.hidden_field :month_approval, :value => @first_day %>
              <div class="form-group">
                <% if @attendance.indicater_reply_month == "承認" %>
                  <%= f.label :indicater_check_month, "所属長承認　#{@attendance.indicater_check_month}から承認済" %>
                <% elsif @attendance.indicater_reply_month == "否認" %>
                  <%= f.label :indicater_check_month, "所属長否認　#{@attendance.indicater_check_month}から否認済" %>
                <% elsif @attendance.indicater_reply_month == "申請中" %>
                  <%= f.label :indicater_check_month, "所属長承認　#{@attendance.indicater_check_month}へ申請中" %>
                <% else %>  
                  <%= f.label :indicater_check_month,"所属長承認 未" %>
                <% end %>  
                  <%= f.collection_select(:indicater_check_month, @superior, :name, :name, {prompt: "上長を選択して下さい"}, {class: "form-control input-sm"})%>
              </div>
              <div class="form-group">
                <%= f.submit '申請', class: 'btn btn-primary' %>
              </div>
          <% end %>
        </td>
      </tr>
    </tfoot> 
  </table>
</div>

<div id= "edit-overtime-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id= "edit-overtime-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id= "edit-one-month-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit-month-approval-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/user_attendance_index.html.erb
<% provide(:title, "index") %>
<h1>出勤中社員一覧</h1>

app/views/users/working.html.erb
<% provide(:title, "working") %>
<h1>出勤中社員一覧</h1>

<div>
  <table class="table table-bordered table-condensed id="table-attendance-index">
    <tr>
      <th>社員番号</th>
      <th>名前</th>
    </tr>

    <% @users.each do |user| %>
      <% user.attendances.each do |attendance| %>
        <% if (Date.current == attendance.worked_on) && 
        attendance.started_at != nil && attendance.finished_at == nil %>
    <tr>
      <td><%=user.employee_number %></td>
      <td><%=user.name %></td>
    </tr>
        <%end%>  
      <%end%>  
    <%end%>  
  </table>
</div>