config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'

  get '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :bases
  resources :users do
    collection { post :import }
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      patch 'update_index'
      # 勤怠変更申請
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'  
      # １ヶ月承認
      get 'attendances/edit_month_approval'
      patch 'attendances/update_month_approval'
      # 確認のshowページ
      get 'verifacation'
    end
    collection do
      get 'working'
    end
    resources :attendances, only: [:update] do
      member do
        # 残業申請モーダル
        get 'edit_overtime_request'
        patch 'update_overtime_request'
        # 残業申請お知らせモーダル
        get 'edit_overtime_notice'
        patch 'update_overtime_notice'
        # 残業申請確認モーダル
        get 'show_overtime_verifacation'
        # 勤怠変更お知らせモーダル
      get 'edit_one_month_notice'
      patch 'update_one_month_notice'
        #１ヶ月承認モーダル
      get 'edit_month_approval_notice'
      patch 'update_month_approval_notice'
      # 勤怠ログ
      get 'log'
      end
    end 
  end
  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  # 指示者確認のカラム not：なし、approval：承認, denial：否認, applying：申請中 
  enum indicater_reply: { "なし" => 0, "承認" => 1, "否認" => 2, "申請中" => 4 }, _prefix: true
  enum indicater_reply_edit: { "なし" => 0, "承認" => 1, "否認" => 2, "申請中" => 4 }, _prefix: true
  enum indicater_reply_month: { "なし" => 0, "承認" => 1, "否認" => 2, "申請中" => 4 }, _prefix: true

  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }




# 勤怠ログ検索
  





  # お知らせモーダルバリデーション
  # validate :check_indicater_reply, on: :update_overtime_notice
  

  


  # def check_indicater_reply
  #   if indicater_reply.present?
  #     errors.add(:indicater_reply, "申請内容を決定して下さい") if change == "0" || change == "1" && indicater_reply == "申請中"
  #   end
  # end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  before_action :set_user, only: [:edit_one_month, :update_one_month, :update_month_approval, :edit_overtime_notice, :edit_one_month_notice, :edit_month_approval_notice]
  before_action :logged_in_user, only: [:update, :edit_one_month]
  before_action :admin_user, only: [:index,:destroy, :edit_basic_info]
  before_action :set_one_month, only: [:edit_one_month]
  before_action :admin_not
  before_action :correct_not, only: [:show, :edit_one_month]
  before_action :correct_user_b, only: [:log]


  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"


  # 残業申請お知らせモーダル
  def edit_overtime_notice
    @users = User.joins(:attendances).group("users.id").where(attendances: {indicater_reply: "申請中"})
    @attendances = Attendance.where.not(overtime_finished_at: nil).order("worked_on ASC")
  end

# 残業申請お知らせモーダル更新
  def update_overtime_notice
    ActiveRecord::Base.transaction do 
      o1 = 0
      o2 = 0
      o3 = 0
      overtime_notice_params.each do |id, item|
        if item[:indicater_reply].present?
          if (item[:change] == "1") && (item[:indicater_reply] == "なし" || item[:indicater_reply] == "承認" || item[:indicater_reply] == "否認")
            attendance = Attendance.find(id)
            user = User.find(attendance.user_id)
            if item[:indicater_reply] == "なし" 
              o1+= 1
              item[:overtime_finished_at] = nil
              item[:tomorrow] = nil
              item[:overtime_work] = nil
              item[:indicater_check] = nil
            elsif item[:indicater_reply] == "承認"
              item[:indicater_check] = nil
              o2 += 1
              attendance.indicater_check_anser = "残業申請を承認しました"
            elsif item[:indicater_reply] == "否認"
              item[:overtime_finished_at] = nil
              item[:tomorrow] = nil
              item[:overtime_work] = nil
              item[:indicater_check] = nil
              item[:indicater_check] = nil
              o3 += 1
              attendance.indicater_check_anser = "残業申請を否認しました"
            end
            attendance.update_attributes!(item)
          end
        else 
          flash[:danger] = "指示者確認を更新、または変更にチェックを入れて下さい"
          redirect_to user_url(params[:user_id])
          return
        end
      end
      flash[:success] = "【残業申請】　#{o1}件なし,　#{o2}件承認,　#{o3}件否認しました"
      redirect_to user_url(params[:user_id])
      return
    end
  rescue ActiveRecord::RecordInvalid 
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to edit_overtime_notice_user_attendance_url(@user,item)
  end
  
# 残業申請モーダル
  def edit_overtime_request
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    @superior = User.where(superior: true).where.not( id: current_user.id )
  end
  
  def update_overtime_request
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    if @attendance.update_attributes(overtime_params)
      flash[:success] = "残業申請を受け付けました"
      redirect_to user_url(@user)
    end  
  end





  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end


# 勤怠変更申請
  def edit_one_month 
    @attendance = Attendance.find(params[:id])
    @superior = User.where(superior: true).where.not( id: current_user.id )
  end 

  def update_one_month
    # カラムを更新した件数を入れる変数を定義
    ActiveRecord::Base.transaction do 
      c1 = 0
      # ストロングパラメーターのidと各カラムを配列で回す
      attendances_params.each do |id,item|
        # Attendanceテーブルから1つのidを見つける
        @attendance = Attendance.find(id)
        # 上長が選択されていること
          if item[:indicater_check_edit].present?
            # 時間が入っていない場合はエラー
            if item[:started_edit_at].blank? && item[:finished_edit_at].present?
              flash[:danger] = "出勤時刻が存在しません"
              redirect_to attendances_edit_one_month_user_url(date: params[:date])
              return
              # 出勤時間が入っていて退勤時間が空場合はエラー
            elsif item[:started_edit_at].present? && item[:finished_edit_at].blank?
              flash[:danger] = "退勤時間が存在しません"
              redirect_to attendances_edit_one_month_user_url(date: params[:date]) 
              return
            elsif item[:started_edit_at].blank? && item[:finished_edit_at].blank?
              flash[:danger] = "時刻を入力して下さい"
              redirect_to attendances_edit_one_month_user_url(date: params[:date]) 
              return
              # 翌日にチェックがなく出勤時間が退勤時間より小さい場合  
            elsif item[:started_edit_at].present? && item[:finished_edit_at].present? && item[:tomorrow_edit] == "0" && item[:started_edit_at].to_s > item[:finished_edit_at].to_s
              flash[:danger] = "時刻に誤りがあります"
              redirect_to attendances_edit_one_month_user_url(date: params[:date])
              return
              # 備考が空の場合
            elsif item[:note].blank?
              flash[:danger] = "変更内容を記入して下さい"
              redirect_to attendances_edit_one_month_user_url(date: params[:date])
              return
            end
              
            # 翌日チェックがあれば
            # if item[:tomorrow] == "1"
            #   # item[:worked_on]で今日の日付を取る。今日か明日かの日付を取る。これを変数tomorrow_dayに代入
            #   tomorrow_day = @attendance.worked_on.tomorrow.to_s
            #   # 退勤時刻のカラム = 上記で作ったtomorrow_dayを文字列にしたもの + 空欄 + 退勤時間を文字列にし、:00を渡すことで日本時間にしてる
            #   item[:finished_edit_at] = tomorrow_day.to_s + " " + item[:finished_edit_at].to_s + ":00"
            # else
            #   # 退勤時刻のカラム = 今日の日付を文字列にしたもの + 空欄 + 退勤時間を文字列にし、:00を渡すことで日本時間にしてる
            #   item[:finished_edit_at] = @attendamce.to_s + " " + item[:finished_edit_at].to_s + ":00"
            # end
            # カラム更新
            c1 += 1
            @attendance.update_attributes!(item)
          end
      end
      if c1 > 0
        flash[:success] = "勤怠変更を#{c1}件受け付けました"
        redirect_to user_url(@user)
      else
        flash[:danger] = "上長を選択して下さい"
        redirect_to attendances_edit_one_month_user_url(date: params[:date])
        return
      end
    end
  rescue ActiveRecord::RecordInvalid 
    flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
    return
  end




# 勤怠変更申請お知らせモーダル
  def edit_one_month_notice
    @users = User.joins(:attendances).group("users.id").where(attendances: {indicater_reply_edit: "申請中"})
    @attendances = Attendance.where.not(started_edit_at: nil, finished_edit_at: nil, note: nil, indicater_reply_edit: nil ).order("worked_on ASC")
  end  

# 勤怠変更申請お知らせモーダル更新
  def update_one_month_notice
    ActiveRecord::Base.transaction do 
      e1 = 0
      e2 = 0
      e3 = 0
      attendances_notice_params.each do |id, item|
      if item[:indicater_reply_edit].present?
        if (item[:change_edit] == "1") && (item[:indicater_reply_edit] == "なし" || item[:indicater_reply_edit] == "承認" || item[:indicater_reply_edit] == "否認")
        attendance = Attendance.find(id)
        user = User.find(attendance.user_id)
          if item[:indicater_reply_edit] == "なし" 
            e1+= 1
            item[:started_edit_at] = nil
            item[:finished_edit_at] = nil
            item[:tomorrow] = nil
            item[:note] = nil
            item[:indicater_check_edit] = nil
          elsif item[:indicater_reply_edit] == "承認"
            if  attendance.started_before_at.blank?
              item[:started_before_at] = attendance.started_at
            end 
            item[:started_at] = attendance.started_edit_at
            if  attendance.finished_before_at.blank?
              item[:finished_before_at] = attendance.finished_at
            end 
            item[:finished_at] = attendance.finished_edit_at
            item[:indicater_check_edit] = nil
            e2 += 1          
            attendance.indicater_check_anser = "勤怠変更申請を承認しました"
          elsif item[:indicater_reply_edit] == "否認"
            item[:started_edit_at] = nil
            item[:finished_edit_at] = nil
            item[:tomorrow] = nil
            item[:note] = nil
            item[:indicater_check_edit] = nil
            e3 += 1
            attendance.indicater_check_edit_anser = "勤怠変更申請を否認しました"   
          end          
          attendance.update_attributes!(item)
        end
      else
          flash[:danger] = "指示者確認を更新、または変更にチェックを入れて下さい"
          redirect_to user_url(params[:user_id])
          return
        end
      end
      flash[:success] = "【勤怠変更申請】　#{e1}件なし,　#{e2}件承認,　#{e3}件否認しました"
      redirect_to user_url(params[:user_id])
      return
    end
    rescue ActiveRecord::RecordInvalid 
      flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
      redirect_to edit_one_month_notice_user_attendance_url(@user,item)
    end



  # 1ヶ月勤怠承認
  def update_month_approval
      # 特定したユーザーの現在の月を取得
      @attendance = @user.attendances.find_by(worked_on: params[:user][:month_approval])
      # パラメーター更新
      # mon = Date.strptime(@attendance.month_approval, format: :short2)
    if month_approval_params[:indicater_check_month].present?
      @attendance.update_attributes(month_approval_params)
      flash[:success] = "勤怠承認申請を受け付けました"
    else  
      flash[:danger] = "上長を選択して下さい"
    end
    redirect_to user_url(@user)
  end  


  def edit_month_approval_notice
    @users = User.joins(:attendances).group("users.id").where(attendances: {indicater_reply_month: "申請中"})
    @attendances = Attendance.where.not(month_approval: nil, indicater_reply_month: nil).order("month_approval ASC")
  end  
  
# 1ヶ月勤怠承認更新

app/helpers/attendances_helper.rb
module AttendancesHelper

  def attendance_state_start(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    return false
  end

  def attendance_state_finish(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    return false
  end

  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end

  
  
  
  # 時間外時間
  def overtime_worked_on(finish, end_time, tomorrow)    
    if tomorrow == true
      # finishとend_timeの時と分をそれぞれ計算し、差分を合わせるために、分側を60で割っている
      format("%.2f", (((finish.hour - end_time.hour) + ((finish.min - end_time.min) / 60.0) + 24)))
    else
      format("%.2f", (((finish.hour - end_time.hour) + ((finish.min - end_time.min) / 60.0))))
    end
  end

end

app/views/attendances/_edit_month_approval_notice.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: @user, url: update_month_approval_notice_user_attendance_path ,method: :patch , local: true) do |f| %>
        <% @users.each do |user|%>
          <h3 align="center" class="modal-title"><%= "【#{user.name}からの1ヶ月分勤怠申請】" %></h3>
            <table class="table table-bordered table-condensed overtime-table">
              <thead class="modal_notice">
                <th>月</th>
                <th>指示者確認
                  <div class="maru size_small black">       
                    <div class="letter3">印</div>
                  </div> 
                </th>
                <th>変更</th>
                <th>勤怠を確認する</th>
              </thead>
                <% @attendances.each do |day| %>
                  <%= f.fields_for "attendances[]", day do |attendance| %>
                    <% if day.user_id == user.id && day.indicater_reply_month == "申請中" && current_user.name == day.indicater_check_month %> 
                      <tbody class="line">
                        <td><%= l(day.month_approval, format: :short2)%>月</td>
                        <td><%= attendance.select :indicater_reply_month, Attendance.indicater_reply_months.keys,{prompt: "選択してください"}, {class: "form-control input-sm" ,required: true } %></td>
                        <td><%= attendance.check_box :change_month %></td>
                        <td><%= link_to "確認", verifacation_user_path(user.id, worked_on: day.worked_on), class: "btn btn-primary", target: :_blank %></td>
                      </tbody>
                    <% end %>
                <% end %>
              <% end %>
            </table>
          <% end %>
          <div class="center">
            <%= f.submit '変更を送信する', class: 'btn btn-primary' %>
          </div>
        <% end %>      
    </div>
  </div>
</div>

app/views/attendances/_edit_one_month_notice.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: @user, url: update_one_month_notice_user_attendance_path, method: :patch, local: true) do |f| %>
        <% @users.each do |user|%>
          <h3 align="center" class="modal-title"><%= "【#{user.name}からの勤怠変更申請】" %></h3>
            <table class="table table-bordered table-condensed one_month_notice-table">
              <thead class="modal_notice">
                <tr>
                  <th rowspan="3">日付</th>
                  <th rowspan="3">曜日</th>
                  <th colspan="4">変更前</th>
                  <th colspan="4">変更後</th>
                  <th rowspan="3">備考</th>
                  <th rowspan="3">指示者確認
                  <div class="maru size_small black">       
                    <div class="letter3">印</div>
                  </div> 
                  </th>
                  <th rowspan="3">変更</th>
                  <th rowspan="3">勤務を確認する</th>
                </tr>
                <tr>
                  <th colspan="2">出社</th>
                  <th colspan="2">退社</th>
                  <th colspan="2">出社</th>
                  <th colspan="2">退社</th>
                </tr>
                <tr>
                  <th>時</th>
                  <th>分</th>
                  <th>時</th>
                  <th>分</th>
                  <th>時</th>
                  <th>分</th>
                  <th>時</th>
                  <th>分</th>
                </tr>
              </thead>
                <% @attendances.each do |day| %>
                  <%= f.fields_for "attendances[]", day do |d| %>       
                    <% if day.user_id == user.id && day.indicater_reply_edit == "申請中" && current_user.name == day.indicater_check_edit %>  
                      <tbody class="line">
                        <% css_class = 
                        case $days_of_the_week[day.worked_on.wday]
                          when '土'         
                          'text-primary'
                          when '日'
                            'text-danger'
                          end
                          %>
                          <td><%= l(day.worked_on, format: :short) %></td>
                          <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
                          <td><%= day.started_at.try(:strftime,"%H") %></td>
                          <td><%= day.started_at.try(:strftime,"%M") %></td>
                          <td><%= day.finished_at.try(:strftime,"%H") %></td>
                          <td><%= day.finished_at.try(:strftime,"%M") %></td>
                          <td><%= day.started_edit_at.try(:strftime,"%H") %></td>
                          <td><%= day.started_edit_at.try(:strftime,"%M") %></td>
                          <td><%= day.finished_edit_at.try(:strftime,"%H") %></td>
                          <td><%= day.finished_edit_at.try(:strftime,"%M") %></td>
                          <td><%= day.note %></td>
                          <td><%= d.select :indicater_reply_edit, Attendance.indicater_reply_edits.keys,{prompt: "選択してください"}, {class: "form-control input-sm" ,required: true } %></td>
                          <td><%= d.check_box :change_edit %></td>
                          <td><%= link_to "確認", verifacation_user_path(user.id, worked_on: day.worked_on), class: "btn btn-primary", target: :_blank %></td>
                      </tbody>
                  <% end %> 
                <% end %>
              <% end %>
            </table>
          <% end %>
            <div class="center">
              <%= f.submit "変更を送信する", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/attendances/_edit_overtime_notice.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: @user, url: update_overtime_notice_user_attendance_path, method: :patch, local: true) do |f| %>
        <% @users.each do |user|%>
          <h3 align="center" class="modal-title"><%= "【#{user.name}からの残業申請】" %></h3>
          <table class="table table-bordered table-condensed overtime_notice-table">
            <thead class="modal_notice">
              <th>日付</th>
              <th>曜日</th>
              <th>終了予定時間</th>
              <th>指定勤務終了時間</th>
              <th>時間外時間</th>
              <th>業務処理内容</th>
              <th>指示者確認
              <div class="maru size_small black">       
                <div class="letter3">印</div>
              </div> 
              </th>
              <th>変更</th>
              <th>勤務を確認する</th>
            </thead>
              <% @attendances.each do |day| %>       
                <%= f.fields_for "attendances[]", day do |d| %>
                  <% if day.user_id == user.id && day.indicater_reply == "申請中" && current_user.name == day.indicater_check %>     
                    <tbody class="line">
                      <% css_class = 
                      case $days_of_the_week[day.worked_on.wday]
                        when '土'
                          'text-primary'
                        when '日'
                          'text-danger'
                        end
                        %>
                        <td><%= l(day.worked_on, format: :short) %></td>
                        <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
                        <td><%= day.overtime_finished_at.try(:strftime,"%H:%M") %></td>
                        <td><%= format_basic_info(user.designated_work_end_time) %></td>
                        <td><%= overtime_worked_on(day.overtime_finished_at, user.designated_work_end_time, day.tomorrow) %></td>
                        <td><%= day.overtime_work %></td>
                        <td><%= d.select :indicater_reply, Attendance.indicater_replies.keys,{prompt: "選択してください"}, {class: "form-control input-sm" ,required: true } %></td>
                        <td><%= d.check_box :change %></td>
                        <td><%= link_to "確認", verifacation_user_path(user.id, worked_on: day.worked_on), class: "btn btn-primary", target: :_blank %></td>
                    </tbody>
                  <% end %>
                <% end %>
              <% end %>
            </table>
        <% end %>
        <div class="center">
          <%= f.submit "変更を送信する", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/attendances/_edit_overtime_request.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">残業申請</h1>
    </div>
    <div class="modal-body">
      <%= form_with(model: @attendance, url: update_overtime_request_user_attendance_path(@user, @attendance) , method: :patch , local: true) do |f| %>
      <%= f.hidden_field :indicater_reply, :value => "申請中" %>
        <table class="table table-bordered table-condensed overtime-table">
          <thead class="overtime_request">
            <th>日付</th>
            <th>曜日</th>
            <th>終了予定時間</th>
            <th>翌日</th>
            <th>業務処理内容</th>
            <th>指示者確認
              <div class="maru size_small black">       
                <div class="letter3">印</div>
              </div> 
            </th>
          </thead>
          <tbody class="line">
            <% css_class = 
            case $days_of_the_week[@attendance.worked_on.wday]
              when '土'
                'text-primary'
              when '日'
                'text-danger'
              end
              %>
            <td><%= l(@attendance.worked_on, format: :short) %></td>
            <td class="<%= css_class %>"><%= $days_of_the_week[@attendance.worked_on.wday] %></td>
            <td><%= f.time_select :overtime_finished_at, {include_blank: true}, {class: "form-control bootstrap-date-only-width",required: true } %></td>
            <td><%= f.check_box :tomorrow,id: "tomorrow" %></td>
            <td><%= f.text_field :overtime_work, {class: "form-control",required: true } %></td>
            <td><%= f.collection_select(:indicater_check, @superior, :name, :name, {prompt: "上長を選択して下さい"}, {class: "form-control input-sm" ,required: true })%></td>
          </tbody>
        </table>
        <%= f.submit "変更を送信する", class: "btn btn-primary btn-block" %>
      <% end %>

    </div>
  </div>
</div>

app/views/attendances/edit_month_approval_notice.js.erb
$("#edit-month-approval-notice").html("<%= escape_javascript(render 'edit_month_approval_notice') %>");
$("#edit-month-approval-notice").modal("show");

app/views/attendances/edit_one_month.html.erb
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出社</th>
          <th>退社</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th>備考</th>
          <th>指示者確認<div class="maru size_small black">       
            <div class="letter3">印</div>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
          <%= attendance.hidden_field :indicater_reply_edit, :value => "申請中" %>

            <% css_class = 
                  case $days_of_the_week[day.worked_on.wday]
                    when '土'
                      'text-primary'
                    when '日'
                      'text-danger'
                    end
            %>
            <tr>
              <td><%= l(day.worked_on, format: :short) %></td>
              <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
              <% if Date.current < day.worked_on %>
                <td><%= attendance.time_field :started_edit_at, class: "form-control", disabled: "true" %></td>
                <td><%= attendance.time_field  :finished_edit_at, class: "form-control", disabled: "true" %></td>
                <td><%= attendance.check_box :tomorrow_edit, id: "tomorrow", disabled: "true"%></td>
                <td>
                  <% if day.started_edit_at.present? && day.finished_edit_at.present? %>
                    <%= str_times = overtime_worked_on(day.finished_edit_at, day.started_edit_at, day.tomorrow_edit) %>
                    <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
                  <% end %>
                </td>
                <td><%= attendance.text_field :note, class: "form-control", placeholder: "変更理由を記載して下さい", disabled: "true" %></td>
                <td><%= attendance.collection_select(:indicater_check_edit, @superior, :name, :name, {include_blank: "上長を選択して下さい"}, {class: "form-control input-sm", disabled: "true" })%></td>
              <% else %>
                <td><%= attendance.time_field :started_edit_at, class: "form-control" %></td>
                <td><%= attendance.time_field  :finished_edit_at, class: "form-control" %></td>
                <td><%= attendance.check_box :tomorrow_edit, id: "tomorrow" %></td>
                <td>
                  <% if day.started_edit_at.present? && day.finished_edit_at.present? %>
                    <%= str_times = overtime_worked_on(day.finished_edit_at, day.started_edit_at, day.tomorrow_edit) %>
                    <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
                  <% end %>
                </td>
                <td><%= attendance.text_field :note, class: "form-control", placeholder: "変更理由を記載して下さい" %></td>
                <td><%= attendance.collection_select(:indicater_check_edit, @superior, :name, :name, {include_blank: "上長を選択して下さい"}, {class: "form-control input-sm" })%></td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="center">
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-primary" %>
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>