config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'

  get '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :bases
  resources :users do
    collection { post :import }
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      patch 'update_index'
      # 勤怠変更申請
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'  
      # １ヶ月承認
      get 'attendances/edit_month_approval'
      patch 'attendances/update_month_approval'
      # 確認のshowページ
      get 'verifacation'
    end
    collection do
      get 'working'
    end
    resources :attendances, only: [:update] do
      member do
        # 残業申請モーダル
        get 'edit_overtime_request'
        patch 'update_overtime_request'
        # 残業申請お知らせモーダル
        get 'edit_overtime_notice'
        patch 'update_overtime_notice'
        # 残業申請確認モーダル
        get 'show_overtime_verifacation'
        # 勤怠変更お知らせモーダル
      get 'edit_one_month_notice'
      patch 'update_one_month_notice'
        #１ヶ月承認モーダル
      get 'edit_month_approval_notice'
      patch 'update_month_approval_notice'
      # 勤怠ログ
      get 'log'
      end
    end 
  end
  get '*not_found', to: 'application#routing_error'
  post '*not_found', to: 'application#routing_error'
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "勤怠システム", '/', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップ",   '/' %></li>

        <% if logged_in? %>

        <% if current_user.admin?%>
        <li><%= link_to "ユーザー一覧", users_path %></li>
        <li><%= link_to "出勤社員一覧", working_users_path %></li>
        <li><%= link_to "拠点情報の修正",bases_path %></li>
        <li><%= link_to "基本情報の修正", edit_basic_info_user_path(current_user) %></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
      <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "勤怠", current_user %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
          <% end %>
        <% else %>
      <li><%= link_to "ログイン", '/login' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application','data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, msg| %>
      <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
    <% end %>  
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      
    </div>
  </body>
</html>